version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/bot/
    stdin_open: true
    tty: true
    command: python fetch_bot.py
  bot2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/bot/
    stdin_open: true
    tty: true
    command: python fetch_bot2.py
